Cleanup
Bench: 1950137

diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -1255,15 +1255,20 @@ net:
 
 format:
 	@echo CLANG_FORMAT=$(CLANG_FORMAT)
-	@if [ -n "$(SRCS)$(HEADERS)" ]; then \
+	@if [ -n "$(CLANG_FORMAT)" ] && [ -n "$(SRCS)$(HEADERS)" ]; then \
 		$(CLANG_FORMAT) -i -style=file $(SRCS) $(HEADERS); \
 	fi
 
 install-hooks:
-	@root="$$(git rev-parse --show-toplevel 2>/dev/null)" || { echo "Not a git repo"; exit 1; }; \
+	@root=$$(git rev-parse --show-toplevel 2> /dev/null); \
+	if [ -z "$$root" ]; then \
+		echo "Not a git repo"; exit 1; \
+	fi; \
 	src="$$root/.git-hooks/pre-commit"; \
 	dst="$$root/.git/hooks/pre-commit"; \
-	if [ ! -f "$$src" ]; then echo "Hook source not found: $$src"; exit 1; fi; \
+	if [ ! -f "$$src" ]; then \
+		echo "Hook source not found: $$src"; exit 1; \
+	fi; \
 	if [ -f "$$dst" ]; then \
 		bak="$$dst.bak.$$(date +%Y%m%d%H%M%S)"; \
 		mv "$$dst" "$$bak" && echo "Existing hook moved to $$bak"; \
@@ -1366,22 +1371,25 @@ FORCE:
 # Clang PGO
 # ------------------------
 clang-profile-make:
+	@rm -rf profdir
+	@mkdir -p profdir
 	$(MAKE) ARCH=$(ARCH) COMP=$(COMP) \
-	EXTRACXXFLAGS='-fprofile-generate' \
-	EXTRALDFLAGS='-fprofile-generate' \
+	EXTRACXXFLAGS='-fprofile-generate=profdir' \
+	EXTRALDFLAGS='-fprofile-generate=profdir' \
 	all
 
 clang-profile-use:
-	$(XCRUN) $(LLVM_PROFDATA) merge -output=$(NAME).profdata *.profraw
+	$(XCRUN) $(LLVM_PROFDATA) merge -output=$(NAME).profdata profdir/*.profraw
 	$(MAKE) ARCH=$(ARCH) COMP=$(COMP) \
 	EXTRACXXFLAGS='-fprofile-use=$(NAME).profdata' \
-	EXTRALDFLAGS='-fprofile-use' \
+	EXTRALDFLAGS='-fprofile-use=$(NAME).profdata' \
 	all
 
 # ------------------------
 # GCC PGO
 # ------------------------
 gcc-profile-make:
+	@rm -rf profdir
 	@mkdir -p profdir
 	$(MAKE) ARCH=$(ARCH) COMP=$(COMP) \
 	EXTRACXXFLAGS='-fprofile-generate=profdir $(EXTRAPROFILEFLAGS)' \
@@ -1391,22 +1399,25 @@ gcc-profile-make:
 gcc-profile-use:
 	$(MAKE) ARCH=$(ARCH) COMP=$(COMP) \
 	EXTRACXXFLAGS='-fprofile-use=profdir -fprofile-correction -fno-peel-loops -fno-tracer $(EXTRAPROFILEFLAGS)' \
+	EXTRALDFLAGS='-fprofile-use=profdir' \
 	all
 
 # ------------------------
 # ICC/ICX PGO
 # ------------------------
 icx-profile-make:
+	@rm -rf profdir
+	@mkdir -p profdir
 	$(MAKE) ARCH=$(ARCH) COMP=$(COMP) \
-	EXTRACXXFLAGS='-fprofile-instr-generate' \
-	EXTRALDFLAGS='-fprofile-instr-generate' \
+	EXTRACXXFLAGS='-fprofile-instr-generate=profdir' \
+	EXTRALDFLAGS='-fprofile-instr-generate=profdir' \
 	all
 
 icx-profile-use:
-	$(XCRUN) $(LLVM_PROFDATA) merge -output=$(NAME).profdata *.profraw
+	$(XCRUN) $(LLVM_PROFDATA) merge -output=$(NAME).profdata profdir/*.profraw
 	$(MAKE) ARCH=$(ARCH) COMP=$(COMP) \
 	EXTRACXXFLAGS='-fprofile-instr-use=$(NAME).profdata' \
-	EXTRALDFLAGS='-fprofile-use' \
+	EXTRALDFLAGS='-fprofile-instr-use=$(NAME).profdata' \
 	all
 
 .depend: $(SRCS)
