Makefile fix
Bench: 2401193

diff --git a/.github/workflows/arm_compilation.yml b/.github/workflows/arm_compilation.yml
--- a/.github/workflows/arm_compilation.yml
+++ b/.github/workflows/arm_compilation.yml
@@ -1,10 +1,12 @@
 name: Android Compilation
+
 on:
   workflow_call:
     inputs:
       matrix:
         type: string
         required: true
+
 jobs:
   Compilation:
     name: "Android build: ${{ matrix.config.name }} ${{ matrix.binaries }}"
@@ -81,10 +83,10 @@ jobs:
             export LDFLAGS="-static -Wno-unused-command-line-argument"
           fi
           make clean
-          make -j4 profile-build ARCH=$BINARY COMP=$COMP RUN_PREFIX=$EMU
-          make strip ARCH=$BINARY COMP=$COMP
+          make -j4 profile-build ARCH="$BINARY" COMP="$COMP" RUN_PREFIX="$EMU"
+          make strip ARCH="$BINARY" COMP="$COMP"
           RUN_PREFIX="$EMU" ../tests/signature.sh "$benchref"
-          mv ./DON$EXT ../DON-android-$BINARY$EXT
+          mv "./DON$EXT" "../DON-android-$BINARY$EXT" || || { echo "ERROR: Built binary ./DON$EXT not found"; exit 1; }
 
       - name: Remove non src files
         run: git clean -fxd
diff --git a/.github/workflows/compilation.yml b/.github/workflows/compilation.yml
--- a/.github/workflows/compilation.yml
+++ b/.github/workflows/compilation.yml
@@ -1,10 +1,12 @@
 name: Compilation
+
 on:
   workflow_call:
     inputs:
       matrix:
         type: string
         required: true
+
 jobs:
   Compilation:
     name: ${{ matrix.config.name }} ${{ matrix.binaries }}
@@ -42,7 +44,7 @@ jobs:
           install: mingw-w64-${{ matrix.config.msys_env }} make git zip
 
       - name: Download SDE package
-        if: ${{ matrix.config.sde }}
+        if: ${{ runner.os == 'Linux' || runner.os == 'Windows' }}
         uses: petarpetrovt/setup-sde@d230e06df0ca06ced70000e4a7fa62afc9a2001e # v4.0
         with:
           environmentVariableName: SDE_DIR
@@ -71,15 +73,15 @@ jobs:
             $COMPCXX -Q -march=native --help=target
           fi
 
-      # Compile the configured release binary.
+      # Compile the configured release binary
 
       - name: Compile ${{ matrix.config.binaries }} build
         run: |
           make clean
-          make -j4 profile-build ARCH=$BINARY COMP=$COMP RUN_PREFIX="$SDE"
-          make strip ARCH=$BINARY COMP=$COMP
+          make -j4 profile-build ARCH="$BINARY" COMP="$COMP" RUN_PREFIX="$SDE"
+          make strip ARCH="$BINARY" COMP="$COMP"
           RUN_PREFIX="$SDE" ../tests/signature.sh "$benchref"
-          mv ./DON$EXT ../DON-$NAME-$BINARY$EXT || { echo "ERROR: Built binary ./DON$EXT not found"; exit 1; }
+          mv "./DON$EXT" "../DON-$NAME-$BINARY$EXT" || { echo "ERROR: Built binary ./DON$EXT not found"; exit 1; }
 
       - name: Remove non src files
         run: git clean -fxd
