Final DON
Bench: 2365512

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -298,12 +298,12 @@ jobs:
           make -j4 ARCH=x86-64-bmi2 optimize=no debug=yes build
           ../tests/signature.sh $benchref
 
-      - name: Test x86-64-avx512 build
+      - name: Test x86-64-avx512icl build
         if: matrix.config.run_64bit_tests && (runner.os == 'Linux' || runner.os == 'Windows')
         run: |
           make clean
-          make -j4 ARCH=x86-64-avx512 build
-          file ./DON 2>/dev/null || file ./DON.exe
+          make -j4 ARCH=x86-64-avx512icl build
+          file ./DON
           #../tests/signature.sh $benchref || echo "Signature test failed with exit code $?"
           echo "=== Running signature ==="
           if ../tests/signature.sh "$benchref"; then
@@ -312,23 +312,30 @@ jobs:
             echo "Signature test failed with exit code $?"
             echo "=== GDB diagnostic ==="
             if command -v gdb >/dev/null 2>&1; then
-              if [ "$RUNNER_OS" = "Windows" ]; then
-                gdb --batch \
-                  -ex "run" \
-                  -ex "x/i \$pc" \
-                  -ex "info registers" \
-                  --args ./DON.exe bench
-              else
-                gdb --batch \
-                  -ex "run" \
-                  -ex "x/i \$pc" \
-                  -ex "info registers" \
-                  --args ./DON bench
-              fi
+              gdb --batch \
+                -ex "run" \
+                -ex "x/10i \$pc-20" \
+                -ex "x/16xb \$pc" \
+                -ex "info registers" \
+                --args ./DON bench
             else
               echo "gdb not installed"
             fi
           fi
+
+      - name: Test x86-64-vnni512 build
+        if: matrix.config.run_64bit_tests
+        run: |
+          make clean
+          make -j4 ARCH=x86-64-vnni512 build
+          ../tests/signature.sh $benchref || echo "Signature test failed with exit code $?"
+
+      - name: Test x86-64-avx512 build
+        if: matrix.config.run_64bit_tests
+        run: |
+          make clean
+          make -j4 ARCH=x86-64-avx512 build
+          ../tests/signature.sh $benchref || echo "Signature test failed with exit code $?"
 
       - name: Test x86-64-bmi2 build
         if: matrix.config.run_64bit_tests
